// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxtjocvcztrmcioemuqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4dGpvY3ZjenRybWNpb2VtdXFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1OTQ4NjEsImV4cCI6MjA3NDE3MDg2MX0.uJhKrjMOt15x9Yz7M1OQna62hMaF6InVWLIu57V2YZw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});